"""Initial migration

Revision ID: 338c75bce295
Revises: 
Create Date: 2025-04-16 18:02:53.339206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338c75bce295'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_users_organization_id_organization')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('date_submitted', sa.DateTime(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_assessment_organization_id_organization')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_assessment_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_readiness_evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('data_availability', sa.Integer(), nullable=True),
    sa.Column('data_quality', sa.Integer(), nullable=True),
    sa.Column('integration_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], name=op.f('fk_data_readiness_evaluation_assessment_id_assessment')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_readiness_evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('ai_skills_level', sa.Integer(), nullable=True),
    sa.Column('training_needs', sa.Text(), nullable=True),
    sa.Column('leadership_support', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], name=op.f('fk_team_readiness_evaluation_assessment_id_assessment')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tech_infra_evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('cloud_ready', sa.Boolean(), nullable=True),
    sa.Column('compute_power_score', sa.Integer(), nullable=True),
    sa.Column('tools_stack_maturity', sa.Integer(), nullable=True),
    sa.Column('apis_ready', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], name=op.f('fk_tech_infra_evaluation_assessment_id_assessment')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('use_case_evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('feasibility', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], name=op.f('fk_use_case_evaluation_assessment_id_assessment')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('use_case_evaluation')
    op.drop_table('tech_infra_evaluation')
    op.drop_table('team_readiness_evaluation')
    op.drop_table('data_readiness_evaluation')
    op.drop_table('assessment')
    op.drop_table('users')
    op.drop_table('organization')
    # ### end Alembic commands ###
